config/urls.py
from django.contrib import admin
from django.urls import path, include

from config.settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include("news.urls")),
    path('reader/', include("reader.urls")),
    path('signup/', signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

news/urls.py
from django.urls import path
from .views import create_news, read_news, update_news, delete_news, view_news, webscrap_news

from config.settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = "news"

urlpatterns = [
    path("create", create_news, name="create-news"),
    path("read", read_news, name="read-news"),
    path("update/<int:pk>", update_news, name="update-news"),
    path("delete/<int:pk>", delete_news, name="delete-news"),
    path("view/<int:pk>", view_news, name="view-news"),
    path("webscrap", webscrap_news, name="webscrap-news"),

] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

news/models.py
from django.db import models
from datetime import datetime
from reader.models import Reader


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    source = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/news/")
    tags = models.TextField(null=True, blank=True, help_text="Write in tag1, Tag2, format")
    views = models.PositiveIntegerField(default=0)
    news_instance = models.DateTimeField(default=datetime.now())

    class Meta:
        verbose_name_plural = "news"

    def __str__(self):
        return str(self.title)


class NewsComment(models.Model):
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/news/comments/")
    file = models.FileField(null=True, blank=True, upload_to="files/news/comments/")
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    comment_instance = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.id)


class NewsVote(models.Model):
    CHOICES = (
        ('Up', 'Up'),
        ('Down', 'Down')
    )
    vote = models.CharField(max_length=255, choices=CHOICES, null=True, blank=True)
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    vote_instance = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.id)

news/forms.py
from django import forms
from .models import News


class CreateNewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ('views', 'news_instance')


class UpdateNewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ('views', 'news_instance')

news/views.py
from django.shortcuts import render, redirect
from .forms import CreateNewsForm, UpdateNewsForm
from .models import News
from .webscrapers import baahrakhari_webscraping
from .webscrapers import ekantipur_webscraping
from .webscrapers import gorkhapatraonline_webscraping
from .webscrapers import onlinekhabar_webscraping
from .sentiment_analyzers import sentiment_intensity_analyzer
from .sentiment_analyzers import textblob_sentiment_analyzer
from .google_translation import google_translation

# Create your views here.
def create_news(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = CreateNewsForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('news:read-news')
        else:
            form = CreateNewsForm()
        context = {
            'form': form
        }
        return render(request, "news/create.html", context)
    else:
        return redirect("news:read-news")


def read_news(request):
    newses = News.objects.all()
    context = {
        "newses": newses
    }
    return render(request, "news/read.html", context)


def update_news(request, pk):
    if request.user.is_superuser:
        required_news = News.objects.get(id=pk)
        if request.method == 'POST':
            form = UpdateNewsForm(instance=required_news,data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                return redirect('news:read-news')
        else:
            form = UpdateNewsForm(instance=required_news)
        context = {
            'form': form
        }
        return render(request, "news/update.html", context)
    else:
        return redirect("news:read-news")


def delete_news(request, pk):
    if request.user.is_superuser:
        required_news = News.objects.get(id=pk)
        if request.method == "POST":
            required_news.delete()
            return redirect('news:read-news')
        return render(request, "news/delete.html")
    else:
        return redirect("news:read-news")


def view_news(request, pk):
    required_news = News.objects.get(id=pk)
    converted_title = google_translation.ArticleConversion(required_news.title)
    converted_description = google_translation.ArticleConversion(required_news.description)
    sia = sentiment_intensity_analyzer.sentiment_analyzer(converted_description)
    # tsa = textblob_sentiment_analyzer.textblob_sentiment_analyzer(converted_text)
    context = {
        "news": required_news,
        "converted_title": converted_title,
        "converted_description": converted_description,
        "positive": sia[0],
        "negative": sia[1],
        "neutral": sia[2],
        "polarity": sia[3]
    }
    return render(request, "news/view.html", context)


def webscrap_news(request):
    baahrakhari_newses = baahrakhari_webscraping.baahrakhari_list_webscraping()
    ekantipur_newses = ekantipur_webscraping.ekantipur_list_webscraping()
    gorkhapatraonline_newses = gorkhapatraonline_webscraping.gorkhapatraonline_list_webscraping()
    onlinekhabar_newses = onlinekhabar_webscraping.onlinekhabar_list_webscraping()
    newses = baahrakhari_newses + ekantipur_newses + gorkhapatraonline_newses + onlinekhabar_newses
    for news in newses:
        registered_news = News.objects.create(title=news[0], image=news[1], source=news[2], description=news[3])
        registered_news.save()
    registered_newses = News.objects.all()
    context ={
        "newses": registered_newses
    }
    return render(request, "news/webscrap.html", context)

news/templates/news/create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
create news
{% endblock %}
{% block content %}
<form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">
            Create News
        </button>
    </form>
{% endblock %}

news/templates/news/delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
create news
{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <h2>Q. Do you want to delete this news?</h2>
    <br>
    <input type="submit" value="Yes"/>
    <a href="{% url 'news:read-news' %}" type="button">Cancel</a>
</form>
{% endblock %}

news/templates/news/read.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
read news
{% endblock %}
{% block content %}
{% for news in newses reversed %}
Id: {{news.id}} <br>
Title: {{news.title}} <br>
<img src="{{news.image}}"><br>
Desc: {{news.description}}<br>
Source: {{news.source}}<br>
Tags: {{news.tags}}<br>
Views: {{news.views}}<br>
Instance: {{news.news_instance}}<br>
{% if request.user.is_superuser %}
<a href="{% url 'news:update-news' news.id %}">Update</a>
<a href="{% url 'news:delete-news' news.id %}">Delete</a>
{% endif %}
<a href="{% url 'news:view-news' news.id %}">View</a>
{% endfor %}
{% endblock %}

news/templates/news/update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
update news
{% endblock %}
{% block content %}
<form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">
            Update News
        </button>
    </form>
{% endblock %}

news/templates/news/view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{{news}}
{% endblock %}
{% block content %}
Id: {{news.id}} <br>
Title: {{news.title}} <br>
<img src="{{news.image}}"><br>
Desc: {{news.description}}<br>
Source: {{news.source}}<br>
Tags: {{news.tags}}<br>
Views: {{news.views}}<br>
Instance: {{news.news_instance}}<br>
Positive: {{positive}}<br>
Negative: {{negative}}<br>
Neutral: {{neutral}}<br>
Polarity: {{polarity}}<br>
Converted Title: {{converted_title}}<br>
Converted Description: {{converted_description}}<br>
{% if request.user.is_superuser %}
<a href="{% url 'news:update-news' news.id %}">Update</a>
<a href="{% url 'news:delete-news' news.id %}">Delete</a>
{% endif %}
 <div id="container">
                <canvas id="pie-chart"></canvas>
            </div>
<script>
                var config = {
                type: 'pie',
                data: {
                    datasets: [{
                        data:[{{positive}}, {{negative}}, {{neutral}}],
                        backgroundColor: [
                            '#00ff80', '#ff6666', '#0080FF',
                        ],
                        label: 'Polarity'
                        }
                        ],
                        labels:['Positive', 'Negative', 'Neutral'],
                        },
                        options: {
                            responsive: true
                        }
                    };

                window.onload = function() {
                    var ctx = document.getElementById('pie-chart').getContext('2d');
                    window.myPie = new Chart(ctx, config);
                };
            </script>
{% endblock %}

news/templates/news/webscrap.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
read news
{% endblock %}
{% block content %}
{% for news in newses %}
Id: {{news.id}} <br>
Title: {{news.title}} <br>
<img src="{{news.image}}"><br>
Desc: {{news.description}}<br>
Source: {{news.source}}<br>
Tags: {{news.tags}}<br>
Views: {{news.views}}<br>
Instance: {{news.news_instance}}<br>
{% if request.user.is_superuser %}
<a href="{% url 'news:update-news' news.id %}">Update</a>
<a href="{% url 'news:delete-news' news.id %}">Delete</a>
{% endif %}
<a href="{% url 'news:view-news' news.id %}">View</a>
{% endfor %}
{% endblock %}